/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import BLL.LoginController;
import BO.Personnel;
import IHM.Personnel.EcranGestionPersonnel;

/**
 *
 * @author Administrateur
 */
public class EcranAccueil extends javax.swing.JFrame {

    /**
     * Creates new form EcranAccueil
     */
    
    private Personnel user;
    private LoginController loginController;
    private Integer sexe;
    private final String user1 = "Connecté en tant que : ";
    private final String user2 = "Connectée en tant que : ";     
    public EcranAccueil() {
        initComponents();
    }
    
    public EcranAccueil(LoginController loginController, Personnel user) {
        initComponents();
        this.loginController = loginController; 
        this.user = user;
        this.lblPrenom.setText(user.getPrenom());
        this.lblNom.setText(user.getNom());
        sexe = user.getSexe();
        if (sexe == 1) {
            this.lblUserCnx.setText(user1);                        
        }
        else {
            this.lblUserCnx.setText(user2);
        }
       
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUserCnx = new javax.swing.JLabel();
        lblPrenom = new javax.swing.JLabel();
        lblNom = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        menuFichier = new javax.swing.JMenu();
        menuItemDeconnexion = new javax.swing.JMenuItem();
        menuItemFermer = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuItemPriseDeRDV = new javax.swing.JMenuItem();
        menuItemGestionDesClients = new javax.swing.JMenuItem();
        menuAgenda = new javax.swing.JMenu();
        menuPersonnel = new javax.swing.JMenu();
        menuItemGestionPersonnel = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 400));

        lblUserCnx.setText("lblUser");

        lblPrenom.setText("prenom");

        lblNom.setText("nom");

        menuFichier.setText("Fichier");
        menuFichier.setMargin(new java.awt.Insets(0, 5, 0, 5));

        menuItemDeconnexion.setLabel("Déconnexion");
        menuItemDeconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDeconnexionActionPerformed(evt);
            }
        });
        menuFichier.add(menuItemDeconnexion);

        menuItemFermer.setLabel("Fermer");
        menuItemFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFermerActionPerformed(evt);
            }
        });
        menuFichier.add(menuItemFermer);

        jMenuBar.add(menuFichier);

        jMenu1.setText("Gestion des rendez-vous");
        jMenu1.setMargin(new java.awt.Insets(0, 5, 0, 5));

        menuItemPriseDeRDV.setText("Prise de rendez-vous");
        menuItemPriseDeRDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPriseDeRDVActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemPriseDeRDV);

        menuItemGestionDesClients.setText("Gestion des clients");
        jMenu1.add(menuItemGestionDesClients);

        jMenuBar.add(jMenu1);

        menuAgenda.setLabel("Agenda");
        menuAgenda.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuBar.add(menuAgenda);

        menuPersonnel.setText("Personnel");
        menuPersonnel.setMargin(new java.awt.Insets(0, 5, 0, 5));

        menuItemGestionPersonnel.setText("Gestion du personnel");
        menuItemGestionPersonnel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemGestionPersonnelActionPerformed(evt);
            }
        });
        menuPersonnel.add(menuItemGestionPersonnel);

        jMenuBar.add(menuPersonnel);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUserCnx)
                .addGap(18, 18, 18)
                .addComponent(lblPrenom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNom)
                .addContainerGap(665, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserCnx)
                    .addComponent(lblPrenom)
                    .addComponent(lblNom))
                .addContainerGap(393, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemPriseDeRDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPriseDeRDVActionPerformed
        new EcranPriseRDV().setVisible(true);
    }//GEN-LAST:event_menuItemPriseDeRDVActionPerformed

    private void menuItemFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFermerActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItemFermerActionPerformed

    private void menuItemGestionPersonnelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemGestionPersonnelActionPerformed
        new EcranGestionPersonnel().setVisible(true);
    }//GEN-LAST:event_menuItemGestionPersonnelActionPerformed

    private void menuItemDeconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDeconnexionActionPerformed
        loginController.deconnexion();
    }//GEN-LAST:event_menuItemDeconnexionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EcranAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EcranAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EcranAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EcranAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EcranAccueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblPrenom;
    private javax.swing.JLabel lblUserCnx;
    private javax.swing.JMenu menuAgenda;
    private javax.swing.JMenu menuFichier;
    private javax.swing.JMenuItem menuItemDeconnexion;
    private javax.swing.JMenuItem menuItemFermer;
    private javax.swing.JMenuItem menuItemGestionDesClients;
    private javax.swing.JMenuItem menuItemGestionPersonnel;
    private javax.swing.JMenuItem menuItemPriseDeRDV;
    private javax.swing.JMenu menuPersonnel;
    // End of variables declaration//GEN-END:variables
}
